language: go

go:
  - 1.6
  - tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get -t ./...

script:
  - go vet
  - bash gotest.sh
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci -repotoken $COVERALLS_TOKEN